I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 185, in script call
    call menuPadrinho1(carta, envelope, jornal)
  File "game/script.rpy", line 80, in script call
    call houseHub(carta, envelope, jornal)
  File "game/script.rpy", line 25, in script call
    call expression "esgotos" pass (mais_um_algo)
  File "game/script.rpy", line 227, in script
    u "Quando você tenta entrar no aposento, é agarrado por trás. Você não consegue ver seu atacante, mas consegue sentir muito bem a ponta de uma adaga contra sua garganta."
Exception: Sayer 'u' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 185, in script call
    call menuPadrinho1(carta, envelope, jornal)
  File "game/script.rpy", line 80, in script call
    call houseHub(carta, envelope, jornal)
  File "game/script.rpy", line 25, in script call
    call expression "esgotos" pass (mais_um_algo)
  File "game/script.rpy", line 227, in script
    u "Quando você tenta entrar no aposento, é agarrado por trás. Você não consegue ver seu atacante, mas consegue sentir muito bem a ponta de uma adaga contra sua garganta."
  File "/home/yuri/Downloads/renpy-6.99.1-sdk/renpy/ast.py", line 573, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/yuri/Downloads/renpy-6.99.1-sdk/renpy/ast.py", line 491, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'u' is not defined.

Linux-3.19.3-200.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
Ren'Py 6.99.1.329
Iluminati Cthullu 0.0
